# Generated by Django 5.1.4 on 2024-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem', models.ImageField(upload_to='media/')),
                ('categoria', models.CharField(choices=[('Entradas', 'Entradas'), ('Sopas', 'Sopas'), ('Carne', 'Pratos de Carne'), ('Peixe', 'Pratos de Peixe'), ('Sobremesas', 'Sobremesas'), ('Sumos', 'Sumos'), ('Vinhos', 'Vinhos'), ('Cafés', 'Cafés')], max_length=50)),
            ],
        ),
    ]
